version: '3.8'

services:
  # 1. El motor de la Base de Datos (PostgreSQL)
  contratacion_db:
    image: postgres:15
    container_name: contratacion_postgres
    restart: always
    environment:
      - POSTGRES_USER=user_contratacion
      - POSTGRES_PASSWORD=pass_contratacion
      - POSTGRES_DB=db_contratacion
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - contratacion_network

  # 2. El Backend en Python (FastAPI + SQLAlchemy + Gemini)
  backend:
    build: ./backend
    container_name: contratacion_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user_contratacion:pass_contratacion@contratacion_db:5432/db_contratacion
      - GEMINI_API_KEY=${GEMINI_API_KEY} # <-- Lee de forma ultra segura tu archivo .env local
    volumes:
      - ./backend:/app
    depends_on:
      - contratacion_db
    networks:
      - contratacion_network

  # 3. El Frontend en JavaScript (React)
  frontend:
    build: ./frontend
    container_name: contratacion_frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - contratacion_network

# Definición de Recursos Compartidos (Redes y Volúmenes)
networks:
  contratacion_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
