version: '3.8'

services:
  # Base de Datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: mvp_postgres_db
    restart: always
    environment:
      - POSTGRES_USER=user_cedula
      - POSTGRES_PASSWORD=pass_cedula
      - POSTGRES_DB=db_cedula
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Backend (FastAPI + IA Gemini)
  backend:
    build: ./backend
    container_name: mvp_fastapi_backend
    restart: always
    ports:
      - "8000:8000"
    # Carga automáticamente todas las llaves del archivo .env local en el contenedor
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://user_cedula:pass_cedula@db:5432/db_cedula
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - db

  # Frontend (React UI)
  frontend:
    build: ./frontend
    container_name: mvp_react_frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:
